# Generated by Django 6.0.3 on 2026-04-05 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_members(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    ProjectMembership = apps.get_model('projects', 'ProjectMembership')
    
    for project in Project.objects.all():
        # 1. Ensure the project owner is an OWNER in ProjectMembership
        if project.owner:
            ProjectMembership.objects.get_or_create(
                project=project,
                user=project.owner,
                defaults={'role': 'owner'}
            )
        
        # 2. Add existing many-to-many members as MEMBER
        # Note: We must use the intermediate table (M2M) which still exists before AlterField
        for member in project.members.all():
            ProjectMembership.objects.get_or_create(
                project=project,
                user=member,
                defaults={'role': 'member'}
            )

def reverse_migrate_existing_members(apps, schema_editor):
    ProjectMembership = apps.get_model('projects', 'ProjectMembership')
    ProjectMembership.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Membership',
                'verbose_name_plural': 'Project Memberships',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.RunPython(migrate_existing_members, reverse_migrate_existing_members),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_projects', through='projects.ProjectMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
